set shell := ["sh", "-uc"]

ponytail-install:
    node ./ponytail/scripts/install.mjs

ponytail-update:
    node ./ponytail/scripts/update.mjs

ponytail-uninstall:
    node ./ponytail/scripts/uninstall.mjs

ask-install:
    node ./ask/scripts/install.mjs

ask-update:
    node ./ask/scripts/update.mjs

ask-uninstall:
    node ./ask/scripts/uninstall.mjs
